/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Start Here",
      items: [{ type: "autogenerated", dirName: "start" }],
    },
    {
      type: "category",
      label: "Harness",
      items: [{ type: "autogenerated", dirName: "harness" }],
    },
    {
      type: "category",
      label: "Workflows",
      items: [{ type: "autogenerated", dirName: "workflows" }],
    },
    {
      type: "category",
      label: "Checklists",
      items: [{ type: "autogenerated", dirName: "checklists" }],
    },
    {
      type: "category",
      label: "Checklist Encyclopedia",
      items: [{ type: "autogenerated", dirName: "checklist-encyclopedia" }],
    },
    {
      type: "category",
      label: "Agents And Skills",
      items: [{ type: "autogenerated", dirName: "agents" }, { type: "autogenerated", dirName: "skills" }],
    },
    {
      type: "category",
      label: "Tools And Connectors",
      items: [{ type: "autogenerated", dirName: "tools-and-connectors" }, "mcp-requirements-generic-on-page-seo"],
    },
    {
      type: "category",
      label: "Schemas",
      items: [{ type: "autogenerated", dirName: "schemas" }],
    },
    {
      type: "category",
      label: "Brand Workspaces",
      items: [{ type: "autogenerated", dirName: "brand-workspaces" }],
    },
    {
      type: "category",
      label: "Implementation Plan",
      items: [{ type: "autogenerated", dirName: "implementation-plan" }],
    },
  ],
};

module.exports = sidebars;
